### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by xiaohaha23** [XiTianGame/xitian-plugin#1]

**Comment by xiaohaha23** [comment]
Error: ENOENT: no such file or directory, scandir 'p
lugins/bin/'
    at Object.readdirSync (node:fs:1405:3)
    at search.read (file:///C:/Users/Administrator.TEST/Desktop/yunzai/Yunzai-Bo
t/plugins/xitian-plugin/module/search.js:94:23)
    at search.startwatch (file:///C:/Users/Administrator.TEST/Desktop/yunzai/Yun
zai-Bot/plugins/xitian-plugin/module/search.js:76:14)
    at new search (file:///C:/Users/Administrator.TEST/Desktop/yunzai/Yunzai-Bot
/plugins/xitian-plugin/module/search.js:11:8)
    at file:///C:/Users/Administrator.TEST/Desktop/yunzai/Yunzai-Bot/plugins/xit
ian-plugin/module/search.js:135:16
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'plugins/bin/'
}

**Comment by XiTianGame** [comment]
在plugins目录下创建bin文件夹就行

**Comment by XiTianGame** [comment]
已经修复，可以尝试更新解决

**Comment by chomoe327** [comment]
我也出现了这个问题，以下是日志


[MiaoYz][14:02:17.606][INFO] 插件管理器1.3.1初始化~
[MiaoYz][14:02:17.663][ERRO] Error: ENOENT: no such file or directory, scandir './plugins/bin/'
    at Object.readdirSync (node:fs:1452:3)
    at search.read (file:///app/Miao-Yunzai/plugins/xitian-plugin/module/search.js:94:24)
    at async search.startwatch (file:///app/Miao-Yunzai/plugins/xitian-plugin/module/search.js:66:3) {

  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './plugins/bin/'
}

我使用docker-compose 部署的miao-yunzai，大概是没有权限创建这个目录？希望能更改下结构把这个目录放到插件本身，不然的话还需要重新映射一个bin目录进去

**Comment by XiTianGame** [comment]
> 我也出现了这个问题，以下是日志
> 
> [苗伊兹][14:02:17.606][INFO] 插件管理器1.3.1初始化~ [MiaoYz][14：02：17.663][ERRO] 错误： ENOENT： 没有这样的文件或目录， scandir './plugins/bin/' at Object.readdirSync （node：fs：1452：3） at search.read （file:///app/Miao-Yunzai/plugins/xitian-plugin/module/search.js:94:24） at async search.startwatch （file:///app/Miao-Yunzai/plugins/xitian-plugin/module/search.js:66:3） { errno： -2， syscall： 'scandir'， code： 'ENOENT'，路径： './plugins/bin/' }
> 
> 我使用docker-compose 部署的miao-yunzai，大概是没有权限创建这个目录？希望能更改下结构把这个目录放到插件本身，不然的话还需要重新映射一个bin目录进去

第一次启动会出现该问题，但不影响后续重启使用，已修复
