### ISSUE TITLE
覆盖安装插件时重命名文件出错

### ISSUE THREAD

**Issue by gelidrain** [XiTianGame/xitian-plugin#5]
作者大大新年快乐哦，我发现了一个bug~
使用“#安装插件”命令后发送js文件，覆盖安装原有插件，会出现以下错误：
```
1|Yunzai-Bot  | [YzBot][15:29:55.008][ERRO] [插件安装][Msg]
1|Yunzai-Bot  | [YzBot][15:29:55.008][ERRO] Error: ENOENT: no such file or directory, rename 'plugins/example私聊测试.js' -> 'plugins/bin/私聊测试.js.bak'
1|Yunzai-Bot  |     at Object.renameSync (node:fs:1026:3)
1|Yunzai-Bot  |     at install (file:///usr/local/Yunzai-Bot/plugins/xitian-plugin/module/install.js:90:11)
1|Yunzai-Bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|Yunzai-Bot  |     at async Install.Msg (file:///usr/local/Yunzai-Bot/plugins/xitian-plugin/apps/Install.js:180:4)
1|Yunzai-Bot  |     at async PluginsLoader.deal (file:///usr/local/Yunzai-Bot/lib/plugins/loader.js:251:52)
```
错误发生在`xitian-plugin/module/install.js`文件的第90行，这一行的代码是``fs.renameSync(`${sameplugin[0].path}${sameplugin[0].file}`, path.join(this.plugins.bin, `${sameplugin[0].file}.bak`))``
应该是`sameplugin[0].path`中提取到的路径末尾不带斜杠导致的，可以用`path.join()`方法把拼接一下。
这里的`path`属性好像是由`search.js`中的解析插件方法`parse()`来赋值的，调用了Node.js的`path.parse()`方法，再将这个方法返回的`dir`属性赋值给`path`，而`dir`得到的文件路径末尾是没有斜杠的，所以这里也没有斜杠。

**Comment by XiTianGame** [comment]
感谢反馈，已修复
