### ISSUE TITLE
载入插件错误

### ISSUE THREAD

**Issue by ghost** [XiTianGame/xitian-plugin#8]
使用Guoba插件一键安装：
```shell
[19:36:17.654][MARK][执行命令] git clone --depth 1 --single-branch https://gitee.com/XiTianGame/xitian-plugin "plugins/xitian-plugin"
[19:36:22.108][MARK][执行命令] git clone --depth 1 --single-branch https://gitee.com/XiTianGame/xitian-plugin "plugins/xitian-plugin" [完成4.453秒] 
Cloning into 'plugins/xitian-plugin'...
[19:36:22.110][MARK][执行命令] cd plugins/xitian-plugin && pnpm install
[19:36:25.248][MARK][执行命令] cd plugins/xitian-plugin && pnpm install [完成3.138秒] 
Scope: all 4 workspace projects
../..                                    | Progress: resolved 0, reused 1, downloaded 0, added 0
../..                                    | Progress: resolved 183, reused 177, downloaded 0, added 0
 WARN  12 deprecated subdependencies found: @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @npmcli/move-file@1.1.2, are-we-there-yet@2.0.0, are-we-there-yet@3.0.1, gauge@3.0.2, gauge@4.0.4, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, npmlog@6.0.2, rimraf@3.0.2
../..                                    | Progress: resolved 621, reused 620, downloaded 0, added 0
../..                                    | Progress: resolved 621, reused 620, downloaded 0, added 0, done

dependencies:
+ acorn 8.12.1

Done in 3s

``` 
重启后：
```shell
[19:36:27.689][MARK][Server] 启动 HTTP 服务器 http://[::]:2536
[19:36:27.691][INFO][Plugin] -----------
[19:36:27.691][INFO][Plugin] 加载插件中...
[19:36:27.742][INFO][TRSSYz] -----------＾ω＾----------
[19:36:27.742][INFO][TRSSYz] 插件管理器2.0.0初始化~
[19:36:27.766][ERRO][TRSSYz] 载入插件错误：Group
[19:36:27.767][ERRO][TRSSYz] Error: ENOENT: no such file or directory, copyfile '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml' -> '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
    at Object.copyFileSync (node:fs:3004:11)
    at ConfigSet.cpCfg (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:184:10)
    at ConfigSet.checkConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:170:14)
    at ConfigSet.getConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:85:10)
    at new pluginLoader (file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:15:24)
    at file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:297:16
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async Promise.allSettled (index 0)
    at async file:///root/Yunzai/plugins/xitian-plugin/index.js:36:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml',
  dest: '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
}
[19:36:27.767][ERRO][TRSSYz] 载入插件错误：Install
[19:36:27.768][ERRO][TRSSYz] Error: ENOENT: no such file or directory, copyfile '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml' -> '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
    at Object.copyFileSync (node:fs:3004:11)
    at ConfigSet.cpCfg (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:184:10)
    at ConfigSet.checkConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:170:14)
    at ConfigSet.getConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:85:10)
    at new pluginLoader (file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:15:24)
    at file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:297:16
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async Promise.allSettled (index 0)
    at async file:///root/Yunzai/plugins/xitian-plugin/index.js:36:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml',
  dest: '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
}
[19:36:27.768][ERRO][TRSSYz] 载入插件错误：List
[19:36:27.768][ERRO][TRSSYz] Error: ENOENT: no such file or directory, copyfile '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml' -> '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
    at Object.copyFileSync (node:fs:3004:11)
    at ConfigSet.cpCfg (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:184:10)
    at ConfigSet.checkConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:170:14)
    at ConfigSet.getConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:85:10)
    at new pluginLoader (file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:15:24)
    at file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:297:16
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async Promise.allSettled (index 0)
    at async file:///root/Yunzai/plugins/xitian-plugin/index.js:36:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml',
  dest: '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
}
[19:36:27.769][ERRO][TRSSYz] 载入插件错误：Manager
[19:36:27.769][ERRO][TRSSYz] Error: ENOENT: no such file or directory, copyfile '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml' -> '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
    at Object.copyFileSync (node:fs:3004:11)
    at ConfigSet.cpCfg (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:184:10)
    at ConfigSet.checkConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:170:14)
    at ConfigSet.getConfig (file:///root/Yunzai/plugins/xitian-plugin/module/config.js:85:10)
    at new pluginLoader (file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:15:24)
    at file:///root/Yunzai/plugins/xitian-plugin/module/loader.js:297:16
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async Promise.allSettled (index 0)
    at async file:///root/Yunzai/plugins/xitian-plugin/index.js:36:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml',
  dest: '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'
}

``` 
Yunzai启动成功后：
```shell
[19:36:27.975][ERRO][TRSSYz] [Guoba] 载入"xitian-plugin"插件的"guoba.support.js"失败：ENOENT: no such file or directory, copyfile '/root/Yunzai/plugins/xitian-plugin//defSet/set/undefined.yaml' -> '/root/Yunzai/plugins/xitian-plugin//config/set.undefined.yaml'

```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by XiTianGame** [comment]
已修复

**Comment by XiTianGame** [comment]
重新拉取或者更新一下
